<b><h2>Assignment No : 13</h2></b>
<h4><b>Problem Statement :</b></h4>
<b><i>Take a matrix of 3x3 and find out the Eigen vector and Eigen values of that matrix.</i></b><br>
<hr>
<br>

In [1]:
import numpy as np

In [2]:
a = np.array([[4,6,10],[3,10,13],[-2,-6,-8]])

In [3]:
val,vec = np.linalg.eig(a)

In [4]:
print("Eigen values:\n",val)

Eigen values:
 [4.00000000e+00 2.00000000e+00 1.00840575e-15]


In [5]:
print("Eigen vectors:\n",vec)

Eigen vectors:
 [[ 0.45749571  0.40824829 -0.57735027]
 [ 0.76249285 -0.81649658 -0.57735027]
 [-0.45749571  0.40824829  0.57735027]]
