<b><h2>Assignment No : 14</h2></b>
<h4><b>Problem Statement :</b></h4>
<b><i>Take a matrix and by taking the i, j or x, y values implement the hstack and vstack 
methods.</i></b><br>
<hr>
<br>

In [1]:
import numpy as np

In [2]:
x = np.arange(0,10,2)
y = np.arange(5)

In [3]:
x

array([0, 2, 4, 6, 8])

In [4]:
y

array([0, 1, 2, 3, 4])

In [5]:
hs = np.hstack([x,y])
vs = np.vstack([x,y])

In [6]:
print("Horizontal Stack :\n",hs)

Horizontal Stack :
 [0 2 4 6 8 0 1 2 3 4]


In [7]:
print("Vertical Stack :\n",vs)

Vertical Stack :
 [[0 2 4 6 8]
 [0 1 2 3 4]]
