<b><h2>Assignment No : 02</h2></b>
<h4><b>Problem Statement :</b></h4>
<b><i>Take 3X3 matrices add it with another 3x3 of all 1 matrix and convert that to a complex 
data type matrix.</i></b><br>
<hr>
<br>

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
c = np.ones((3,3))
d = a+b+c

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [5]:
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
d

array([[12., 14., 16.],
       [18., 20., 22.],
       [24., 26., 28.]])

In [7]:
new = d.astype(np.complex128)

In [8]:
new

array([[12.+0.j, 14.+0.j, 16.+0.j],
       [18.+0.j, 20.+0.j, 22.+0.j],
       [24.+0.j, 26.+0.j, 28.+0.j]])