<b><h2>Assignment No : 05</h2></b>
<h4><b>Problem Statement :</b></h4>
<b><i>Randomly generate 10 numbers in between 1 to 10 and convert that to a 5X2 matrix. Take a floating-point matrix and perform the addition. a = floating point matrix and b is an integer matrix of same dimension. Why a+=b is not equal to b+=a. Explain briefly. How can we resolve this problem ?</i></b><br>
<hr>
<br>

In [1]:
import numpy as np

In [2]:
b = np.random.randint(1,11,size=10)
b = b.reshape(5,2)
a = np.array([[1.1,2.2],
            [3.3,4.4],
            [5.5,6.6],
            [7.7,8.8],
            [9.9,10.0]])

In [3]:
a += b

In [4]:
b += a

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

<br><b>Array b contains integers (int32) and array a contains floating-point numbers (float64). When the operation a+=b performed it means addition of integer values from array a to floating-point values in array b. It does not give error because element of b added with integer part of a and the result is a floating point number which is also the datatype of a.<br><br>But b+=a throw an error because element of b is a floating point number and we are trying to add with and store it in element of a, which leads to a data type mismatch, and NumPy cannot automatically perform this operation while preserving the data types. It does not allow the conversion from float64 to int32 without potential loss of precision.<br><br>That's why here a+=b and b+=a are not same.<br><br><br><br><br><br><br><br><br><br><br>To avoid this error, we should make sure that the data types of the arrays involved in element-wise operations are compatible. We can do this by ensuring that both arrays have the same data type or by explicitly converting one of the arrays to the data type of the other (using astype)  before performing the operation.</b><br><br>

In [5]:
b1 = np.random.randint(1,11,size=10)
b1 = b1.reshape(5,2)
a1 = np.array([[1.1,2.2],
            [3.3,4.4],
            [5.5,6.6],
            [7.7,8.8],
            [9.9,10.0]])

In [6]:
b1_new = b1.astype(np.float64)

In [7]:
a1 += b1_new

In [8]:
b1_new += a1

In [9]:
a1

array([[ 5.1, 10.2],
       [ 8.3,  7.4],
       [ 9.5,  8.6],
       [17.7, 11.8],
       [19.9, 11. ]])

In [10]:
b1

array([[ 4,  8],
       [ 5,  3],
       [ 4,  2],
       [10,  3],
       [10,  1]])

In [11]:
b1_new

array([[ 9.1, 18.2],
       [13.3, 10.4],
       [13.5, 10.6],
       [27.7, 14.8],
       [29.9, 12. ]])